apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-flink-config
  labels:
    app: {{ template "fullname" . }}
data:
  flink-conf.yaml: |
    blob.server.port: 6124
    jobmanager.rpc.address: {{ template "fullname" . }}-jobmanager
    jobmanager.rpc.port: 6123
    jobmanager.heap.mb: {{ .Values.flink.jobmanager_heap_mb }}
    taskmanager.heap.mb: {{ .Values.flink.taskmanager_heap_mb }}
    taskmanager.numberOfTaskSlots: {{ .Values.flink.num_slots_per_taskmanager }}
  log4j.properties: |
{{.Files.Get "config/log4j.properties" | indent 4}}
  logback.xml: |
{{.Files.Get "config/logback.xml" | indent 4}}
